language: minimal

services:
  - docker

install:
  - docker-compose up -d app

script:
  - docker-compose run test

deploy:
  provider: npm
  email: "npm@enrise.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
